application:
  port: 8000
  hmac_secret: "long-and-very-secret-rnadom-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
  authorization_token: "POSTMARK_API_TEST"
  timeout_milliseconds: 10000
